USE `bank_db`;

CREATE TABLE `user` (
	`id` INTEGER NOT NULL AUTO_INCREMENT,
	`login` VARCHAR(200) NOT NULL UNIQUE,
	`password` VARCHAR(200) NOT NULL,
	/*
	 * 0 - CLIENT
	 * 1 - CASHIER
	 * 2 - MANAGER
	 * 3 - ADMIN
	 */
	`role` TINYINT NOT NULL,
	PRIMARY KEY (`id`)
) ENGINE=INNODB DEFAULT CHARACTER SET utf8;

CREATE TABLE `client` (
	`id` INTEGER NOT NULL,
	`account_id` VARCHAR(200) NOT NULL UNIQUE,
	`balance` BIGINT NOT NULL,
	`is_active` BOOLEAN NOT NULL,
	PRIMARY KEY (`id`),
	FOREIGN KEY (`id`) REFERENCES `user` (`id`) ON UPDATE RESTRICT ON DELETE RESTRICT
) ENGINE=INNODB DEFAULT CHARACTER SET utf8;

CREATE TABLE `transfer` (
	`id` INTEGER NOT NULL AUTO_INCREMENT,
	`source_id` INTEGER,
	`destination_id` INTEGER,
	`date` TIMESTAMP NOT NULL,
	`sum` BIGINT,
	PRIMARY KEY (`id`),
	FOREIGN KEY (`source_id`) REFERENCES `client` (`id`) ON UPDATE RESTRICT ON DELETE RESTRICT,
	FOREIGN KEY (`destination_id`) REFERENCES `client` (`id`) ON UPDATE RESTRICT ON DELETE RESTRICT
) ENGINE=INNODB DEFAULT CHARACTER SET utf8;
